### ISSUE TITLE
Dynamically initialise phone input fields?

### ISSUE THREAD

**Issue by 01Kuzma** [jackocnr/intl-tel-input#921] opened 2019-06-20 20:02 UTC
Hi there!
Thank you for the great plug-in!

This question is a bit more related to jQuery, but maybe do someone has a working example?
I've many forms on one page. Each of the forms should have a phone number field. 
But in order to make the `intl-tel-input` work with phone number fields, they should have unique names.
So I'm getting a big number of fields which should be properly initialized. 
If I will do it manually I will get:
forms * phone input fields = number of initializations. 
So, if my init code looks like:
```
	var input = document.querySelector("#phone2"),
	  errorMsg = document.querySelector("#error-msg"),
	  validMsg = document.querySelector("#valid-msg");

	var errorMap = [ "Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];

	var iti = window.intlTelInput(input, {
	
	  initialCountry: "auto",
	  geoIpLookup: function(callback) {
		$.get('proxy.php', function() {}).always(function(resp) {
		  var countryCode = (resp && resp.country) ? resp.country : "";
		  callback(countryCode);
		});
	  },	
	  hiddenInput: "full_phone",
	  utilsScript: "intlTelInput/js/utils.js"
	});

	var reset = function() {
	  input.classList.remove("error");
	  errorMsg.innerHTML = "";
	  errorMsg.classList.add("hide");
	  validMsg.classList.add("hide");
	};

	input.addEventListener('blur', function() {
	  reset();
	  if (input.value.trim()) {
		if (iti.isValidNumber()) {
		  validMsg.classList.remove("hide");
		} else {
		  input.classList.add("error");
		  var errorCode = iti.getValidationError();
		  errorMsg.innerHTML = errorMap[errorCode];
		  errorMsg.classList.remove("hide");
		}
	  }
	});

	input.addEventListener('change', reset);
	input.addEventListener('keyup', reset);
```
I have to copy and paste it for each field. How could I avoid it?
How it could be done dynamically?

Many thanks!

**Comment by jackocnr** [comment] 2019-06-21 09:31
I would extract your init code into a function, and then use `document.querySelectorAll()` to select all of your inputs where you want to init the plugin, and then loop over them, and for each one call your new init function.

If you want them all the have different hidden input names, the best thing to do is to use the square bracket feature of the `hiddenInput` option. Check the readme for more info, but basically if you give your inputs names that include square brackets e.g. `<input name="phone1[main]" />` and then init the plugin with the `hiddenInput` option set to "full", then in this case the hidden input will be given the name "phone1[full]". Then give your next input the name "phone2[main]" and it will get a hidden input with name "phone2[full]" etc.

I hope that answers your question. I'll close this for now, but I'm happy to re-open if you have any more questions.

**Closed by jackocnr** 2019-06-21 09:31 UTC

**Comment by 01Kuzma** [comment] 2019-06-21 10:12
Thank you!
So, basically the input will be without `id`, like:
`<input type="tel" class="phone" name="phone_tab2[main]" required="">`

Then `document.querySelectorAll()` will loop through all `name's` of input and paste name attributes into `window.intlTelInput`?

**Comment by jackocnr** [comment] 2019-06-21 10:23
> Then document.querySelectorAll() will loop through all name's of input and paste name attributes into window.intlTelInput?

No, you use `document.querySelectorAll()` to select all of your inputs, then you loop over them and for each one you call your new init function. As far as I can see your init function should be exactly the same for each input.

**Comment by 01Kuzma** [comment] 2019-06-21 10:56
Now I'm trying to init the plugin with square brackets, in order to go further, but getting this error: `TypeError: input is null`

The input in markup looks like: `<input type="tel" class="phone" name="phone_tab1[main]" required="">`

**JS**:
```
    var input;

    function PhoneDisplay(assignedName){
      let PhoneNumer = document.querySelector(`input[name="${assignedName}"]`);
      input = window.intlTelInput(PhoneNumer, {
		  hiddenInput: "full",
		  initialCountry: "auto",
		  geoIpLookup: function(callback) {
			$.get('proxy.php', function() {}).always(function(resp) {
			  var countryCode = (resp && resp.country) ? resp.country : "";
			  callback(countryCode);
			});
		  },	
		  hiddenInput: "full_phone",
		  utilsScript: "intlTelInput/js/utils.js"
      });
	  
		var reset = function() {
		  input.classList.remove("error");
		  errorMsg.innerHTML = "";
		  errorMsg.classList.add("hide");
		  validMsg.classList.add("hide");
		};

		input.addEventListener('blur', function() {
		  reset();
		  if (input.value.trim()) {
			if (iti.isValidNumber()) {
			  validMsg.classList.remove("hide");
			} else {
			  input.classList.add("error");
			  var errorCode = iti.getValidationError();
			  errorMsg.innerHTML = errorMap[errorCode];
			  errorMsg.classList.remove("hide");
			}
		  }
		});

		input.addEventListener('change', reset);
		input.addEventListener('keyup', reset);	  	  	  
    }

    PhoneDisplay("phone_tab1[full]");
   // or  PhoneDisplay("phone_tab1"); doesn't make sense
```
What I'm doing wrong?

**Comment by jackocnr** [comment] 2019-06-21 11:10
I wouldn't select on name, I would add a class to all of your inputs e.g. `class="phone"` and then select on that.

Also I wouldn't do the selection inside the function, I would do it outside e.g. document.querySelectorAll('.phone') - this will select all of your inputs, then loop through those, calling your function and each time pass in the input.

**Comment by 01Kuzma** [comment] 2019-06-21 20:16
Thank you for you answers!

strange... I have a few inputs in different markup places:
```
<input type="tel" class="phone_flag" name="phone_tab1[main]" required="">
<input type="tel" class="phone_flag" name="phone_tab2[main]" required="">
<input type="tel" class="phone_flag" name="phone_tab3[main]" required="">
```

and loop through them:
```
    document.querySelectorAll('.phone_flag').forEach(el => {	
        PhoneDisplay(el.className);		
    });
	
    function PhoneDisplay(ClassName){
	
      var input = document.querySelector('.' + `${ClassName}`);	  
      var iti = window.intlTelInput(input, {
		  hiddenInput: "full",
		  initialCountry: "auto",
		  geoIpLookup: function(callback) {
			$.get('proxy.php', function() {}).always(function(resp) {
			  var countryCode = (resp && resp.country) ? resp.country : "";
			  callback(countryCode);
			});
		  },	
		  hiddenInput: "full_phone",
		  utilsScript: "intlTelInput/js/utils.js"
      });
	  
		var reset = function() {
		  input.classList.remove("error");
		  errorMsg.innerHTML = "";
		  errorMsg.classList.add("hide");
		  validMsg.classList.add("hide");
		};

		input.addEventListener('blur', function() {
		  reset();
		  if (input.value.trim()) {
			if (iti.isValidNumber()) {
			  validMsg.classList.remove("hide");
			} else {
			  input.classList.add("error");
			  var errorCode = iti.getValidationError();
			  errorMsg.innerHTML = errorMap[errorCode];
			  errorMsg.classList.remove("hide");
			}
		  }
		});

		input.addEventListener('change', reset);
		input.addEventListener('keyup', reset);	  	  	  
    }
```

but only the very first input is initialized, while others are not...

**Comment by jackocnr** [comment] 2019-06-22 08:57
Not all browsers support `forEach` on the result of `querySelectorAll` - instead you should use a regular `for` loop. And when you call your `PhoneDisplay` function, don't pass in the class name, instead pass in the element itself, and in `PhoneDisplay` just initialise the plugin on that element directly.

Anyway at this point this is just standard JavaScript use, this is not specific to the plugin any more, so if you're still having problems I'd recommend asking for help on StackOverflow.

**Comment by 01Kuzma** [comment] 2019-06-22 09:03
Thank you!

**Comment by 01Kuzma** [comment] 2019-06-23 12:38
I hope it will be the last question :)
I've made initialization following your advice. And it's working! 
Only one issue left - the validation doesn't work once the multiple inputs are initialized. While with a single item it is working.
Any clues? Suggestions? Or it is a bug?

Many thanks!

**The working code**:
```
	let ary = Array.prototype.slice.call(document.querySelectorAll(".phone_flag"));
	
	ary.forEach(function(el) {
		PhoneDisplay(el);
	})	
	
    function PhoneDisplay(input){		
	 var errorMsg = document.querySelector("#error-msg"),
	     validMsg = document.querySelector("#valid-msg");

	 var errorMap = [ "Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];	
	      
      var iti = window.intlTelInput(input, {
		  hiddenInput: "full",
		  initialCountry: "auto",
		  geoIpLookup: function(callback) {
			$.get('proxy.php', function() {}).always(function(resp) {
			  var countryCode = (resp && resp.country) ? resp.country : "";
			  callback(countryCode);
			});
		  },			  
		  utilsScript: "intlTelInput/js/utils.js"
      });
	  
		var reset = function() {
		  input.classList.remove("error");
		  errorMsg.innerHTML = "";
		  errorMsg.classList.add("hide");
		  validMsg.classList.add("hide");
		};

		input.addEventListener('blur', function() {
		  reset();
		  if (input.value.trim()) {
			if (iti.isValidNumber()) {
			  validMsg.classList.remove("hide");
			} else {
			  input.classList.add("error");
			  var errorCode = iti.getValidationError();
			  errorMsg.innerHTML = errorMap[errorCode];
			  errorMsg.classList.remove("hide");
			}
		  }
		});

		input.addEventListener('change', reset);
		input.addEventListener('keyup', reset);	  	  	  
    }
```

**Comment by jackocnr** [comment] 2019-06-23 13:14
> the validation doesn't work once the multiple inputs are initialized

What do you mean it doesn't work? Please describe the steps you are taking, what you expect to happen, and what actually happens, and be as specific as possible.

In fact the best way to help me understand would be to reproduce the problem in a Codepen. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by 01Kuzma** [comment] 2019-06-23 14:30
[Here it is](https://codepen.io/01kuzma/pen/dBWRXE). 

Please don't pay attention to the layout. I've removed mostly everything.

On the working site, the logic is simple, There are buttons, pressing them tabs with inputs are revealed and user fill in the data into inputs. Once the submit button is pressed - the validator checks all inputs and sends the data into a separate script.

In codepen I've left only two "Order" buttons. Pressing the first - opens the tab with the working validator, while clicking on the second "Order" button will open the second tab where validator fails to initialize.

So, I've observed that only the first input is working correctly with validation: if I enter characters in the first form or enter other not valid data - the message "Invalid country code" or other error message is displayed. 
But If I click on the second "Order" button and enter any data into phone input - the validation just doesn't work... And the same situation with the other inputs (more than 20) which I've on my local site

**Comment by jackocnr** [comment] 2019-06-23 16:16
Yeah the problem is that you have multiple elements with ID "error-msg". `querySelector` will only ever select the first one it finds. Also IDs should be unique.

One potential solution is to switch those IDs to be classes instead (e.g. ".error-msg"), and instead of selecting all inputs and iterating over them and passing each input into the function, instead select all of your containers (".tab-pane"), and iterate over those, and pass each tab pane element into the function. Then inside the function, you'll need to select the input within that tab pane (something like `tabPane.querySelector(".phone")`), and likewise, select the error-msg element within that tab pane for your error handling code.

Again, this is just JavaScript, it's nothing to do with the plugin, so if you have any further questions, I'd recommend asking for help on StackOverflow.
