### ISSUE TITLE
Convert flags.png to AVIF format to comply with PageSpeed Insights recommendation

### ISSUE THREAD

**Issue by rashadmehtab** [jackocnr/intl-tel-input#1605] opened 2024-05-08 09:17 UTC
1. **Description**:
   - **Issue**: PageSpeed Insights is flagging our website for not serving images in next-generation formats.
   - **File**: flags.png
   - **Format**: AVIF (AV1 Image File Format)
   - **Objective**: Convert flags.png to AVIF format to improve website performance and comply with PageSpeed Insights recommendation.

2. **Additional Information**:
   - Converting images to AVIF can significantly reduce image file sizes, leading to faster page load times and improved user experience.
   - It's important to ensure browser compatibility when serving AVIF images. Most modern browsers support AVIF, but fallback options or feature detection may be necessary for older browsers.

**Comment by jackocnr** [comment] 2024-05-08 09:36
Thanks for raising this. I agree it would be a good idea to provide this. It looks like AVIF is supported by all major browsers so assuming the filesize is smaller than PNG then we should switch and use this instead. I would welcome a PR that implemented this.

**Comment by bronisMateusz** [comment] 2024-05-20 12:39
Additionally, as part of this PR, it would be possible to finally equalise the height of all the flags, as they look awful when each one is a different height.

**Comment by bronisMateusz** [comment] 2024-05-20 20:54
@jackocnr I have started working on a fix today, all flags will be in 4:3 aspect ratio and most likely in `.avif` format.

**Comment by jackocnr** [comment] 2024-05-21 08:07
This sounds great, thanks. I'm interested to see what you come up with regarding the flag ratios. Bear in mind that there will have to be some kind of compromise somewhere as not all flags have the same ratios e.g. Switzerland, Nepal, Vatican city, Sri Lanka etc etc

**Comment by vladsfh** [comment] 2024-05-21 16:41
> @jackocnr I have started working on a fix today, all flags will be in 4:3 aspect ratio and most likely in `.avif` format.

4:3 aspect ratio-d flags would be amazing and drastically reduce styles

**Comment by jackocnr** [comment] 2024-06-07 10:55
@bronisMateusz is there any update on this?

The simple solution, to just provide AVIF format, would just be to add an extra build step to convert the PNG files into AVIF files.

**Comment by bronisMateusz** [comment] 2024-06-07 10:57
@jackocnr Sorry, I currently had other topics on my mind, but I should be releasing something over the weekend. Forgive me for waiting so long.

**Comment by bronisMateusz** [comment] 2024-06-19 19:45
@jackocnr Again, sorry it took so long, but I have finally prepared a PR with changes: [https://github.com/jackocnr/intl-tel-input/pull/1666](https://github.com/jackocnr/intl-tel-input/pull/1666)

**Comment by jackocnr** [comment] 2024-06-22 12:13
As outlined in the PR discussion, unfortunately this implementation won't work. I've created a separate issue for switching to consistent 4:3 ratio flags here: https://github.com/jackocnr/intl-tel-input/issues/1668

Until that gets implemented, I would be open to a PR that just adds an extra [build step](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-the-flag-images) to convert the existing flag sprite (and globe) PNGs into AVIF format.

**Comment by djmj** [comment] 2024-07-16 18:27
Instead of raster format consider vector SVG format. This should also improve pagespeed That would enhance render quality of the component and there are some githubs out there which could be used:

https://flagicons.lipis.dev/

**Comment by jackocnr** [comment] 2024-07-16 22:07
@djmj thanks for the suggestion, but I've looked into this before and the SVGs are always much larger in filesize than a PNG sprite, and AVIF is much smaller than a PNG, so I'd like to prioritise smaller filesize and hence faster loading times in this case.

**Comment by bronisMateusz** [comment] 2024-07-17 04:23
Yes, I can confirm that too, my first idea was to use `.svg` too, but in this case `.avif` gives the best results.

**Comment by jackocnr** [comment] 2024-07-17 21:25
Released in v23.5.0. I ended up going with webp, which seemed to be better for logo images, and I went for a lossless conversion, resulting in a significant filesize decrease. You can get way more reduction in filesize if you have a lossy conversion, but i thought the decrease in quality was too noticeable e.g. on the black pattern on the Albania flag.

**Closed by jackocnr** 2024-07-17 21:25 UTC
Labels: enhancement, needs-dev

**Comment by EdwardNavarro** [comment] 2024-08-01 17:20
Hi guys, any way to config plugin to use PNG instead of WEBP? This update broke some of our app due to WEBP incompatibility and restrictions to use WEBP. This update sound great for anybody looking for performance improvements for PageSpeed, CWV and so on, but other users may not want or couldn't use WEBP natively.

Thanks in advance for any advice on how to do it

**Comment by jackocnr** [comment] 2024-08-01 18:07
@EdwardNavarro the PNGs are still there in the /build/img/ directory, so in your CSS you just have to specify the paths to the PNG files instead of the WEBP files (see the Getting Started section of the readme).

Out of interest, what exactly wasn't compatible with WEBP? Was it a particular browser/version, or device/OS or something? I checked [caniuse](https://caniuse.com/webp) and it says all modern browsers support WEBP.

**Comment by EdwardNavarro** [comment] 2024-08-01 18:33
@jackocnr that not solves the issue because WEBP files still in the exported build. In our case, the problem is that we can't have WEBP files inside the build due to platform restrictions, in this case Shopify. :'(

**Comment by jackocnr** [comment] 2024-08-01 22:30
@EdwardNavarro can you please open a new issue describing your problem in as much detail as possible, e.g. what you mean when you say "WEBP files still in the exported build" - I don't understand what this is referring to. Please include clear steps to reproduce the issue you're seeing.
