### ISSUE TITLE
Entering a single digit results in an error of undefined instead of too short

### ISSUE THREAD

**Issue by lee-tms** [jackocnr/intl-tel-input#1466] opened 2023-09-12 16:29 UTC
### Steps to reproduce
1.  Go to the demo page https://intl-tel-input.com/examples/validation-practical.html
2.  Enter a single digit value (i.e. 1 or 2 or 8) and click Validate
3.  Error message appears as undefined
4. Add an extra digit (to make, for example, 22) and click Validate
5. Error message now states Too short

### Expected behaviour
The error should not be undefined and should also return Too short

### Actual behaviour
An error that isn't handled is returned, resulting in undefined

![image](https://github.com/jackocnr/intl-tel-input/assets/5928040/b0e31b74-3118-4c6d-9359-38cc20157e70)

![image](https://github.com/jackocnr/intl-tel-input/assets/5928040/f0bc9287-4eee-4092-bf8a-33bc27f9bfd5)

**Comment by jackocnr** [comment] 2023-10-09 12:09
I can confirm this occurs with both isValidNumber and isPossibleNumber. It looks like we need to tweak the [getValidationError](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/utils.js#L67) function somehow to catch this situation. I don't have time to look into this myself at the moment, but would welcome a pull request that fixes this.

**Comment by jackocnr** [comment] 2024-01-12 19:00
Fixed in master. Will be included in next release - either today or tomo.

**Closed by jackocnr** 2024-01-12 19:00 UTC
Labels: bug, needs-dev
