### ISSUE TITLE
Wrong padding-left setting

### ISSUE THREAD

**Issue by ppalella** [jackocnr/intl-tel-input#1092] opened 2020-05-18 23:57 UTC
When initializing the input, the value of padding-left is defined as style = "padding-left: 1525px;"

To solve this problem, I added this line in the intlTelInput.js file, at line 927

`if (selectedFlagWidth> 100) selectedFlagWidth = 90;`

My initial configuration is

```
window.intlTelInput(input, {
    separateDialCode: true,
    utilsScript: 'vendor/intl-tel-input/build/js/utils.js',
});
```
HTML
`<input class="form-control kt-phone col-sm-5" autocomplete="off" name="phone" type="number" id="item-phone" placeholder="Phone number">
`

**Comment by jackocnr** [comment] 2020-05-25 10:42
Duplicate of #965

**Closed by jackocnr** 2020-05-25 10:42 UTC
