### ISSUE TITLE
Use hiddenInput when more than one phone input in form?

### ISSUE THREAD

**Issue by LucyI** [jackocnr/intl-tel-input#738] opened 2018-05-24 14:52 UTC
This is a remarkable script - thank you!

I'm wondering if it's possible to use hiddenInput: "full_phone" when there is more than one phone input in the form... I searched the issues but haven't found this use case mentioned.

Seems to grab the value from the last input. Here's a pen, submitting will post to Codepen to see values:
[https://codepen.io/followingsea/pen/JvVgNG/](https://codepen.io/followingsea/pen/JvVgNG/)

**Comment by jackocnr** [comment] 2018-05-25 12:00
Good catch. So it is indeed creating two hidden inputs, but the problem is that they both have the same name, so only the last one gets sent. I think the solution is to use the value you provide for the `hiddenInput` option as a suffix to the original input name. So if you have 2 phone inputs, one with name `phone1` and the other `phone2` (like in your example), then you initialise the plugin with `hiddenInput: 'full'`, then the first hidden input will have the name `phone1full` and the second will be `phone2full` - what do you think?

**Comment by LucyI** [comment] 2018-05-25 15:04
That seems like a great solution. :)

**Comment by dogseven** [comment] 2018-05-26 10:27
Excellent answer, thanks. Just what I was looking for.

**Comment by jackocnr** [comment] 2018-05-26 14:40
Ok great. Unfortunately I don't have time to implement this myself any time soon, but I'm open to pull requests :)

**Comment by hamidyousefi** [comment] 2018-06-12 11:19
@LucyI and @jackocnr 
I have a question and another solution if you are accept it, I can implement it and send a pull request!

Question is why we need to have `hiddenInput` with different name? it is not better way that if we want to have 2 different value related to same field, we use arrays? for example, in this example, the result like this is not acceptable?

```
phone1[main] = aaaa
phone1[hidden] = xxxaaaa
phone2[main] = bbbb
phone2[hidden] = zzzbbbb
```

**Comment by jackocnr** [comment] 2018-06-12 11:39
Hmm yes I think this is a cleaner approach, thanks @hamidyousefi. I would propose we keep the `hiddenInput` option as taking a string, and that becomes the array index, and using "main" for the visible input, like you suggest. So in your example, if you initialised the plugin with `hiddenInput` set to "full", then you'd get:

```
phone1[main] = aaaa
phone1[full] = xxxaaaa
phone2[main] = bbbb
phone2[full] = zzzbbbb
```

I'd welcome a pull request to this effect, thanks!

**Comment by hamidyousefi** [comment] 2018-06-12 12:00
@jackocnr I sent a pull request with more explanations. if you have time please check it!

**Comment by jackocnr** [comment] 2018-07-23 12:59
This was fixed by https://github.com/jackocnr/intl-tel-input/commit/42aaa4b7fd24768bd2232db2cd9061b18709c233 and will be in the next release.

**Closed by jackocnr** 2018-07-23 12:59 UTC
Labels: bug, needs-dev
