### ISSUE TITLE
Flag css offset not calculated on prefilled form when page is coming from cache

### ISSUE THREAD

**Issue by mnatator** [jackocnr/intl-tel-input#1181] opened 2020-12-06 11:50 UTC
### Steps to reproduce
1.  Fully refresh page (flag shows correctly, background-position-x is correctly set to show the right flag for an already filled in number)
2.  Reload page (without clearing cache, for example using f5) 
3.  

### Expected behaviour
With a prefilled form it should show the correct flag corresponding to the country code of the prefilled phone number. 

### Actual behaviour
In nearly all cases it shows an empty (grey) flag. The css background-position-x of the flags.png background is not properly set. 

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries
utilsScript: "{url}/js/utils.js",
preferredCountries: ["gb","de","nl","be"],
onlyCountries: ["at", "be", "bg", "hr", "ca", "cy", "cz", "dk", "ee", "fi", "fr", "de", "gr", "hu", "ie", "it", "lv", "lt", "lu", "mt", "nl", "no", "pl", "pt", "ro", "sk", "si", "es", "se", "ch", "us", "gb"]

**Comment by jackocnr** [comment] 2021-01-08 09:26
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by frocentus** [comment] 2021-01-24 15:28
I had this problem too, unfortunately I was not able to reproduce it on a Code-Pen, but I found a workaround that did the trick for me.

The problem occured here, when the form-element with the phone-number is prefilled with a value. On first load, it showed the flag correct, on a refresh the class with the country-code is not set.

My workaround is to leave the value of the input-element empty, and instead fill it with the correspondening js call:

`iti.setNumber('+43 664 12345678');`

Maybe this helps to drill the issue down.

**Comment by jackocnr** [comment] 2021-02-07 11:11
I'd need to see this problem in action to be able to help debug it. Could either of you link me to a live website where this is happening? Or even better, create a new blank page on your website with just the minimal code required to reproduce the issue?

**Comment by frocentus** [comment] 2021-02-07 15:45
Hi, I put an example on my site, have a look @ [https://www.reisinger.ws/iti/](https://www.reisinger.ws/iti/) => On first load it works, when reloading the page, the flag disappears.

But one important thing I found today, it happens - in my case - only in **Firefox** (I have Version 85.0 (64-Bit)). It worked in Chrome, Edge (Chromium), IE11 and Vivaldi Browser.

**Comment by jackocnr** [comment] 2021-02-07 17:49
Thanks for that - thats a great help. Would it be possible to reduce the JS to just the very minimum required to reproduce the issue? Probably that would just be `window.intlTelInput(input, {separateDialCode: true})` but I'm not sure.

And then can we confirm that setting `separateDialCode:false` fixes the problem?

**Comment by frocentus** [comment] 2021-02-07 18:01
Thank you for the feedback, I stripped out some code, and some UI-Elements, and updated the page.

And, your guess with that `separateDialCode:false` is right, it fixes the problem.

**Comment by jackocnr** [comment] 2021-02-07 18:53
Hmm the issue is that when you refresh, Firefox is ignoring the value attribute sent in the page markup e.g. `<input value="+4366412345678" />` and instead it's persisting the real current (typed) value in the input which is "66412345678", and when you initialise the plugin with that value, it's missing the country code so there's no way to know which flag to show.

I've just pushed a fix for this - can you see if the latest release solves the problem for you?

**Comment by frocentus** [comment] 2021-02-07 20:01
I updated the page to use the new version and it works like a charm, thank you very much for the fix!

**Comment by jackocnr** [comment] 2021-02-07 20:06
Great :)

**Closed by jackocnr** 2021-02-07 20:06 UTC
