### ISSUE TITLE
AQ- Antartica is Missing in the Library. 

### ISSUE THREAD

**Issue by ragav-india** [jackocnr/intl-tel-input#929] opened 2019-07-03 08:43 UTC
Hi, 

I am getting an error message. 

>  No country data for 'aq'
>     at Iti._getCountryData (intlTelInput.js:872)

I referred [this ](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/country-sync.html) . There also country Antartica (AQ), Code  +672 is missing.

**Comment by jackocnr** [comment] 2019-07-03 09:01
Duplicate of #125

**Closed by jackocnr** 2019-07-03 09:01 UTC
