### ISSUE TITLE
isValidNumber() passing on invalid number

### ISSUE THREAD

**Issue by NickSutton** [jackocnr/intl-tel-input#1535] opened 2024-02-27 10:46 UTC
### Steps to reproduce
1.  Select UK ('gb') as the intended country
2.  Enter 7 digits of the mobile number
3.  I am using:

````
      $("#tel").on("keyup", function () {
        if (iti.isValidNumber()) {
          $(".swal2-confirm").focus();
        }
      });
````

which focuses the confirm button at length = 7 instead of the full length number for the UK.

### Expected behaviour
Should only pass after 11 digits (ie, 07123 012345) or 10 digits if the number begins +44 +447123 012345

### Actual behaviour
isValidNumber() is passing when length is 7 for UK format numbers

### Initialisation options
````
        autoInsertDialCode: true,
        initialCountry: 'gb',
        nationalMode: false,
        utilsScript: "assets/InternationalTel_dev/build/js/utils.js",
````

**Comment by jackocnr** [comment] 2024-02-27 20:28
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by NickSutton** [comment] 2024-02-28 17:19
Hi,

Thanks for this, tests pass correctly on the test site.

**Comment by jackocnr** [comment] 2024-02-29 13:53
Thanks for raising this. I can confirm that `isValidNumber` is incorrectly returning true for UK numbers of 7-10 digits (as you say it should only be true for UK numbers of 11 digits). I think this is because technically, in the UK, you can dial local numbers of 7 digits and they work fine. But obviously, that is not useful for us in this context.

The quick fix is to switch to `isValidNumberPrecise` which should work as expected. You can check the readme for more info on the difference between these two methods.

I will explore this issue further with libphonenumber, the lib we use for validation, and see if we can find a way to fix it. So I'll leave this issue open for now.

**Comment by jackocnr** [comment] 2024-03-02 15:20
I think it's unlikely we will get any help from LPN any time soon, so I've added a workaround for this for now, which fixes `isValidNumber` for UK mobile numbers at least. Released in v19.5.5.

**Comment by jackocnr** [comment] 2024-03-06 16:54
The below screenshot is from the Wikipedia page for [Telephone numbers in the United Kingdom](https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom?oldformat=true#Format) shows that there are valid UK numbers (after the leading 0) of length 7, 9 and 10. (It also shows valid numbers of shorter lengths e.g. dialing "999" for emergency services, but I think libphonenumber excludes numbers like those)

So in this case, we would have to find a way to exclude 08 (toll free) numbers lengths from the validation. Perhaps we only want to include mobile and fixed-line numbers? I think that would be fine for most use cases. So I'll look into this next. Ideally we'd find a way to exclude all the meta data for other number types, to reduce the bundle size, but I don't know if this is possible - I'll ask on the LPN discussion thread, linked above.

<img width="432" alt="Screenshot 2024-03-06 at 16 46 50" src="https://github.com/jackocnr/intl-tel-input/assets/1186883/8be77c26-4daf-4fb1-b3dd-9d0982a37880">

**Comment by jackocnr** [comment] 2024-03-06 17:22
Ok I'm going to re-open this issue, as I've found a way to move forwards, but don't have time to implement it right now.

In utils.js, in the `isPossibleNumber` method, we should be using the LPN method `isPossibleNumberForTypeWithReason` and specifying a number type each time e.g. MOBILE or FIXED_LINE. I think that by default it should be mobile only, which I think will be the use case for the vast majority of people, but we can have an argument `mobileOnly` which defaults to true, but the dev can set it to false and then it will check for all number types.

One implementation note is that when it is set to mobile-only, we need to do one isPossible check for `numberType.MOBILE` (e.g. `isPossibleMobile`), and one for `numberType.FIXED_LINE_OR_MOBILE` (e.g. `isPossibleFixedLineOrMobile`) and at the end, return `isPossibleMobile || isPossibleFixedLineOrMobile`.

**Comment by NickSutton** [comment] 2024-03-07 05:23
Hi, I think the last comment hits the nail on the head.

For the UK, mobile numbers can be 07 or +44 if using the international prefix. For example: 07111 012345 = +447111 012345

01 numbers will be a landline of a residence or business. I've never actually heard of a 7-digit number, it looks like they are newer toll-free options. 

I think the `mobileOnly` argument would help, for sure.

**Comment by jackocnr** [comment] 2024-03-07 13:42
Just noting here that [LPN have said](https://groups.google.com/g/libphonenumber-discuss/c/H-VVzK0AArM/m/n_46YW0sBAAJ) there is no way to include/exclude the metadata for specific number types unfortunately.

**Closed** 2024-03-07 14:53 UTC

**Comment by jackocnr** [comment] 2024-03-07 15:08
Released in v19.5.6

**Comment by NickSutton** [comment] 2024-03-21 10:56
> `isValidNumber(mobileOnly)` option released in v19.5.6

Unfortunately, I am still seeing the original issue, when called `iti.isValidNumber(true)` on UK registered mobile numbers such as +447123012345 and 07123456789

**Comment by jackocnr** [comment] 2024-03-21 11:21
I'm confused, the original issue was about isValidNumber returning true for invalid numbers, but the two number examples you just shared are valid, no?

**Comment by NickSutton** [comment] 2024-03-21 12:17
Those two numbers are valid, but `isValidNumber(true)` is passing earlier than it should, as per the initial post, it would seem, at '07123 01'

**Comment by jackocnr** [comment] 2024-03-21 13:02
That's strange, I can't reproduce that on [the validation demo](https://intl-tel-input.com/examples/validation-practical.html) - if I select GB and enter "07123 01" and click Validate it says "Invalid number". (Note that this demo is using v20.0.5, where mobileOnly is true by default, so no need to pass true to isValidNumber). Can you make sure you're using the latest version?

**Comment by NickSutton** [comment] 2024-03-21 13:13
My bad… The JS and CSS was updated, but the utils script was not! Now it’s working as expected. Sorry!
