### ISSUE TITLE
getInstance not working in jQuery-wrapped version

### ISSUE THREAD

**Issue by iflow** [jackocnr/intl-tel-input#1060] opened 2020-03-25 16:14 UTC
### Steps to reproduce
1.  Create a new intl-tel-input instance:  `$jqueryElement.intlTelInput();`
2.  Try to get the instance afterwards: `window.intlTelInputGlobals.getInstance($jqueryElement[0])`
3.  The result is undefined.

This only happens in the jQuery-wrapped version.
After comparing the pure JS version with the jQuery-wrapped one, the issue may belongs to the missing attribute _data-intl-tel-input-id_ which gets never set in the jQuery-wrapped version.

Since the development of the jQuery-wrapped version has lower priority, correct me if I'm wrong, I will stick to the pure JS version - the migration is quite easy :)
`window.intlTelInput($jqueryElement[0])`

**Comment by jackocnr** [comment] 2020-03-26 16:00
Dupe of #956 

But yes I do recommend you use the pure version!

**Closed by jackocnr** 2020-03-26 16:00 UTC

**Comment by emreerkan** [comment] 2022-05-18 10:47
If I read the code correctly you can get the instance via the jQuery elements `data` attribute;

```
var iti = $jqueryElement.data('plugin_intlTelInput');
iti.isValidNumber();
```
