### ISSUE TITLE
Flag switches automatically while typing phone number

### ISSUE THREAD

**Issue by MaartenPetiet** [jackocnr/intl-tel-input#1866] opened 2024-11-01 08:50 UTC
### Plugin version
v24.6.0

### Steps to reproduce
1.  Open dropdown and select "Aland Islands"
2.  Start typing phone number "457"
3. Flag switches to Finland

### Expected behaviour
I'm not sure if this is a bug or feature, but I would expect that that the flag never switches without the user explicitly doing that. If the typed phone number does not comply with the formatting rules of that region it should trigger a validation message.

### Actual behaviour
The flag switches to the Finnish flag.

### Initialisation options
Setting `separateDialCode: true` will trigger this behavior. With `seperateDialCode: false` it doesn't do this, which leads me to suspect this is a bug.

**Comment by jackocnr** [comment] 2024-11-04 14:16
Hmm interesting. Thanks for raising this as it has highlighted a few things I need to clear up.

This is working as intended in the case of separateDialCode=true. It should also do the same when nationalMode=false, although I've just found an unrelated bug in this case (select Aland Islands, then type dial code +358, and it selects Finland), which I will fix. Ideally, in my opinion, it would also update the selected flag as you type with the default options (separateDialCode=false and nationalMode=true), but this is harder to achieve as area codes are more complicated to handle in national numbers e.g. in the UK, there is an extra digit ("0") inserted at the beginning of the area code. I will also add this to my to-do list, to make it consistent at least.

Additionally, I've just spotted another issue - this time the problem is with libphonenumber: when separateDialCode=true, and you select Aland Islands, the placeholder number starts with a 4, which is not a valid Aland Islands number - it's actually a Finnish number, and if you type it, it will (correctly) change the flag to Finland. The problem is the generated number we get from libphonenumber is incorrect, so I will file an issue with them.

> I would expect that that the flag never switches without the user explicitly doing that

The thing is, the user can always type a plus and then a new international dial code, which surely should change the selected flag, right? And if you accept that, then why stop there? e.g. both Bahamas and Bermuda have the +1 dial code, but if you type +1242 then that can only be a Bahamas number, or +1441 can only be a Bermuda number, so why not update the flag?

> If the typed phone number does not comply with the formatting rules of that region it should trigger a validation message

It seems strange to me to let the user type a full valid number, and then fail validation because it doesn't match the selected flag. Then what does the error message say - please update the flag selection to match the typed number? That seems quite annoying for the user.

To be clear, we're talking about an edge case here, because to follow your steps to reproduce - if you select Aland Islands and then type 457, you're not typing an Aland Islands number - you're typing a Finish number, so the user is already behaving strangely here.

What do you think?

**Comment by MaartenPetiet** [comment] 2024-11-05 17:58
Thanks for your detailed reply @jackocnr. I am mainly aiming for consistency here, so that you found some issues here that can be improved helps a lot!

> To be clear, we're talking about an edge case here, because to follow your steps to reproduce - if you select Aland Islands and then type 457, you're not typing an Aland Islands number - you're typing a Finish number, so the user is already behaving strangely here.

I agree. This is definitely an edge case, so if this is something that would cost way too much time to fix/change I would totally understand.

> It seems strange to me to let the user type a full valid number, and then fail validation because it doesn't match the selected flag. Then what does the error message say - please update the flag selection to match the typed number? That seems quite annoying for the user.

Yes that's an interesting and valid point. I agree that it would be annoying if a user needs to change the flag just to get the validation to succeed. The reason I am/was expecting an error message is that I assume a user doesn't select the wrong region by accident. If the user then makes a typo and we can catch that, that would be great. But I acknowledge this is an assumption of mine. Maybe a user just clicks the first correct dial code it sees and doesn't mind which region it shows. Then it would definitely be annoying if we would force the user to change it.

I see pros and cons for both methods and just wanted to confirm that this behavior is expected. Whatever method you think is best works for me!

**Comment by jackocnr** [comment] 2024-11-06 18:44
UPDATE: for reference, there are 36 countries where we store area code information, and 24 of those are NANP countries, which don't have any national number prefixes, so they should be trivial to get working. Here are the other 12 countries:

<img width="705" alt="Screenshot 2024-11-06 at 18 41 51" src="https://github.com/user-attachments/assets/2eefda09-0e97-4d39-98a4-fb1316bdc419">

So we'd need to check the national number rules for all of these countries (/territories/regions).

**Comment by jackocnr** [comment] 2024-11-06 19:23
No national prefix:
- Caribbean Netherlands
- Svalbard
- Vatican City

National prefix "0":
- Aland Islands
- Christmas Islands
- Cocos Islands
- Guernsey
- Isle of Man
- Jersey
- Mayotte
- Western Sahara

National prefix "8":
- Kazakhstan

So we'll need to encode this national prefix digit in the [country data](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intl-tel-input/data.ts), and then the easiest way to implement this would probably be to just add a few more entries into `this.dialCodeToIso2Map` to include the national prefixed version as well e.g. when adding "441624" for Isle of Man, notice that Isle of Man has a national prefix digit if "0", so also add "4401624".

**Comment by jackocnr** [comment] 2024-12-08 16:58
I've now fixed these issues in v25.1.1. Give it a try and let me know if you have any issues. Thanks again for reporting this.

**Closed by jackocnr** 2024-12-08 16:58 UTC
Labels: bug, needs-dev
