### ISSUE TITLE
NANP phone number error

### ISSUE THREAD

**Issue by fracsi** [jackocnr/intl-tel-input#529] opened 2017-01-03 10:36 UTC
### Steps to reproduce
1.  Enter a phone number with prefix from a NANP country eg. +12642351234 in this example: http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/national-mode.html

### Expected behaviour
The country is selected as Anguilla. And the international number is from `getNumber` call: +12642351234

### Actual behaviour
The country is selected as Anguilla, but the international number becomes: 264+12642351234
The dialcode without the +1 is added to the number again.

### Initialisation options
`{separateDialCode: false}`

**Comment by jackocnr** [comment] 2017-01-04 09:37
Confirmed. Thanks for reporting this. The problem is in the _getFullNumber method - we need to handle the case when `val` includes a +1 (as well as the case where it doesn't). Unfortunately I wont be able to fix this for the next few days, but would welcome a pull request.

**Comment by jackocnr** [comment] 2017-01-07 23:57
Fixed in v10.0.3

**Closed by jackocnr** 2017-01-07 23:57 UTC
Labels: bug, needs-dev
