### ISSUE TITLE
Change of country sometimes removes digits

### ISSUE THREAD

**Issue by tomas-nz** [jackocnr/intl-tel-input#1089] opened 2020-05-16 09:21 UTC
### Steps to reproduce
1.  Type in a number +1 473-403-1234 (Grenada)
2.  Change the country to Bahamas

### Expected behaviour
Replace +1 473 with +1 242

### Actual behaviour
Replaces +1 473 with +1. So the resulting phone number becomes +1-403-1234 and the country flag then changes to Canada.

### Initialisation options
    const phones = [];
    document.querySelectorAll('.phone').forEach((item, index) => {
        // set initial country code for empty phone numbers
        const phone = window.intlTelInput(item, {
            utilsScript: "{% static 'core/intlTelInput/utils.js' %}",
            initialCountry: countryCode.value,
            nationalMode: false
        });
        item.addEventListener('change', () => {
            const ext = phone.getExtension();
            phone.setNumber(phone.getNumber() + (ext ? ' ext. ' + ext : ''));
        });
        phones.push(phone);
    });

**Comment by tomas-nz** [comment] 2020-05-21 09:10
I was able to reproduce the same behaviour on this demo page: https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/display-number.html

**Comment by jackocnr** [comment] 2020-05-25 10:34
I can reproduce this, thanks for reporting. We should check if the country you're switching from and to - if they both only have a single area code, then that should be factored into the dial code switch.

Note that if you change from Grenada to USA, you will still see this issue as the USA has many possible area codes and we wouldn't know which one you wanted. Perhaps we should also add a special case for this where if you're changing to a country with multiple area codes that we just leave the existing area code and assume they will update it manually. But then at the first keypress, if they don't change the area code, the plugin would immediately change the flag back to Grenada, because if you leave the +1473 at the beginning, then that can only be a Grenada phone number. Still I think it makes sense. What do you think?

**Comment by tomas-nz** [comment] 2020-05-26 10:05
Our main concern is that if a user changes the country by accident and then changes it back, that they get the original phone number back too. So from that perspective the second scenario (changing Grenada to USA) would be best handled by keeping the original area code.

**Comment by jackocnr** [comment] 2020-05-26 10:23
Ok great. 

I'm afraid I don't have time to work on this myself right now, but would welcome a pull request.

**Comment by tomas-nz** [comment] 2020-05-29 10:04
@jackocnr Please see https://github.com/jackocnr/intl-tel-input/pull/1100
I am still learning the ropes so would appreciate any comments/guidance.

Regarding the changes: I thought not changing the area codes at all would be the safest and would make the behaviour consistent (instead of changing it but only if both source and target have a single area code). What do you think?

**Comment by jackocnr** [comment] 2020-05-30 13:34
Fixed in v17.0.3.

**Closed by jackocnr** 2020-05-30 13:34 UTC
Labels: bug, needs-dev
