### ISSUE TITLE
Accessibility Issue

### ISSUE THREAD

**Issue by wileysuraj** [jackocnr/intl-tel-input#1240] opened 2021-06-08 03:01 UTC
### Expected behavior
To solve the accessibility issue we can add appropriate role

### Actual behavior
Error for accessibility
Required ARIA child role not present: textbox

### For Reference
this.selectedFlag = this._createEl("div", {
                        "class": "iti__selected-flag",
                        role: "combobox",
                        "aria-controls": "iti-".concat(this.id, "__country-listbox"),
                        "aria-owns": "iti-".concat(this.id, "__country-listbox"),
                        "aria-expanded": "false"
                    }, this.flagsContainer);

**Comment by rwinikates** [comment] 2021-06-18 15:55
Using the axe devtool chrome extension, you can get a bit more detail on this for context. This is rated a critical issue and a WCAG 2.0 (A) Must.

The ARIA role on the `.iti__selected-flag` div must contain particular children, such as an aria role of textbox.  More info on this available here: https://dequeuniversity.com/rules/axe/4.2/aria-required-children

**Comment by rwinikates** [comment] 2021-07-12 17:49
I believe this is a duplicate of #1194

**Closed** 2023-04-07 11:16 UTC
