### ISSUE TITLE
Padding: padding left issue for input 

### ISSUE THREAD

**Issue by srikanthreddy919** [jackocnr/intl-tel-input#965] opened 2019-09-08 08:19 UTC
I am using input in bootstrap modal, but it's adding padding left the size of window. please help me on this.
I have noticed issue in the below code 
```js
var selectedFlagWidth = this.selectedFlag.offsetWidth || this._getHiddenSelectedFlagWidth()
```
if `this.selectedFlag.offsetWidth` equal to `0` it's excuting `this._getHiddenSelectedFlagWidth()`

but this function should modify like below 

```js
 {
                key: "_getHiddenSelectedFlagWidth",
                value: function _getHiddenSelectedFlagWidth() {
                    // to get the right styling to apply, all we need is a shallow clone of the container,
                    // and then to inject a deep clone of the selectedFlag element
                    var containerClone = this.telInput.parentNode.cloneNode();
                    containerClone.style.visibility = "hidden";
                    // to get the right width for selected flag make container position absolute
                    containerClone.style.position = "absolute"; //fix for padding issue
                    document.body.appendChild(containerClone);
                    var selectedFlagClone = this.selectedFlag.cloneNode(true);
                    containerClone.appendChild(selectedFlagClone);
                    var width = selectedFlagClone.offsetWidth;
                    containerClone.parentNode.removeChild(containerClone);
                    return width;
                }
            }
```

![intltelinput-padding](https://user-images.githubusercontent.com/14222311/64485328-ef874080-d23c-11e9-9019-702f73f93f3c.png)

**Comment by massmediagroup-73** [comment] 2019-09-10 07:22
The version  "16.0.3" has the same problem.

**Comment by jackocnr** [comment] 2019-09-11 08:42
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by JavierPAYTEF** [comment] 2019-09-14 07:30
I have the same issue, the problem appears if the separateDialCode is set to true. On initialization it attempts to calculate padding-left with the selected country but doesn't detect one.
Even thought initialCountry is set and it appears to have something selected. The control also doesn't reflect the selection in the placeholder also, in the screenshot it's blank.

I did some more tests, and if I delay the initialization for a second then it loads fine, so it's probably something that didn't load while it's calculating the padding (maybe the styles or the flags, not sure).

I'm trying to reproduce in the workbench but can't do it.

One thing to notice is I'm loading the source on webpack with npm, so it's likely I'm messing things there.

**Comment by JavierPAYTEF** [comment] 2019-09-14 07:45
Sorry for the spam, but I managed to fix it if I make sure the CSS for int-tel-input is loaded before the javascript is executed.
If the CSS is lazy loaded or deferred after the javascript runs the styles are updated, and that's why the control is properly formated, but the padding is calculated without styles which is why it has an invalid value.

This can't be reproduced in CodePen, because the problem is most likely caused by loading order which can't be changed there.

I'm guessing the only way to reproduce it is with webpack and lazy loading the scss. Since lazy load is done through javascript, by the time it loads the styles the initialization code already ran.

**Comment by leikoilja** [comment] 2019-09-16 09:29
Oh, I have the same problem now, having left padding being wrongly calculated on the plugin initialization, if i run `setNumber` :confused:. Will try to look into fixes as @JavierPAYTEF has proposed

**Comment by jackocnr** [comment] 2019-09-16 09:45
Yes by definition this will need the CSS to be loaded in order for the initialisation (with `separateDialCode`) to work properly. I'm afraid that is a requirement for this particular setup. So the solution is to make sure the plugin CSS has loaded before initialising the plugin in the JS. I'll close this for now, but if this doesn't work for anyone please post here and we can continue discussing.

**Comment by nitsujri** [comment] 2019-10-05 01:20
For anyone else coming across this issue, building on @JavierPAYTEF, the laziest solution I came up with was to wait until the `load` event is fired (post images load). 

    `addEventListener('load', () => {...`

So many drawbacks to waiting that late that I cannot recommend it, so here's when I foresee it not working:

- CSS lazy loaded and ultra slow network. CSS still gets loaded after `load` is fired.
- Connection dies before images finish loading, whole plugin will only load after timeout ~1minute?

I believe the only definitive solution would be to separately load the CSS and then fire an event if you're doing a lazy loading the CSS.

**Comment by JavierPAYTEF** [comment] 2019-10-08 08:38
I think the issue that should be resolved is to avoid defaulting to "screen width" if the CSS fails to load. Adding a max value or maybe a hardcoded default would be appropriate in this case. Maybe it won't look correct but at least it will be usable.
Otherwise when the padding fails the control is unusable and breaks the layout of the entire page.

**Comment by AhedKabalan** [comment] 2019-11-27 11:20
It seems you're using bootstrap modal.
please try the following code:

`$('#exampleModal').on('shown.bs.modal', function (e) {
  	var input = document.querySelector("#phone");
	window.intlTelInput(input, {
	    separateDialCode: true,
	});
});`

**Comment by vanilla-thunder** [comment] 2019-11-27 12:03
I had the same issue.
If you use something like angularjs, that removes/adds dom elements, you can force it being rendered when it becomes visible: 
`<div ng-if="shouldBeVisible"><input .... ></div>`

**Comment by Zippovich2** [comment] 2019-12-18 09:48
Hi guys, I hope my case will help someone. 
In my case I add css for making input width 100%:
```css
.iti{
    width: 100%;
}
```
Where is a problem? If we look at `intlTelInput-jquery.js` 923-925 lines:
```js
var selectedFlagWidth = this.selectedFlag.offsetWidth || this._getHiddenSelectedFlagWidth();
// add 6px of padding after the grey selected-dial-code box, as this is what we use in the css
this.telInput.style.paddingLeft = "".concat(selectedFlagWidth + 6, "px");
```
and 948-960 lines:
```js
key: "_getHiddenSelectedFlagWidth",
value: function _getHiddenSelectedFlagWidth() {
    // to get the right styling to apply, all we need is a shallow clone of the container,
    // and then to inject a deep clone of the selectedFlag element
    var containerClone = this.telInput.parentNode.cloneNode();
    containerClone.style.visibility = "hidden";
    document.body.appendChild(containerClone); // problem is here on 954 line
    var selectedFlagClone = this.selectedFlag.cloneNode(true);
    containerClone.appendChild(selectedFlagClone);
    var width = selectedFlagClone.offsetWidth;
    containerClone.parentNode.removeChild(containerClone);
    return width;
}
```
What happens here? If block with input is hidden then `offsetWidth` return 0 and script will create clone node at the end of body and will get width of flags container from clone, but if you add css like me which make this block `width:100%` `_getHiddenSelectedFlagWidth` return wrong value, it return width of body.

My solution was simple:
```css
.form-group .iti{
    width: 100%;
}
```

**Comment by raysunqi** [comment] 2020-01-16 17:58
Had the same issue with bootstrap modal and angularJS, the problem is that js code is executed before UI is rendered so that `this.selectedFlag.offsetWidth` returns 0, and `this._getHiddenSelectedFlagWidth()` return the width of the browser window(without the scroll bar).
in this line.
`var selectedFlagWidth = this.selectedFlag.offsetWidth || this._getHiddenSelectedFlagWidth();`

My fix is to do adding a ng-if in the modal so that UI is rendered later. However I think the logic to calculate selectedFlagWidth needs to be revisited, at least not returning the with the of screen when UI is not ready.

**Comment by AlekseyMelikov** [comment] 2020-01-23 05:04
+1 i also have this problem

**Comment by binDongKim** [comment] 2020-02-12 07:58
I figured this issue is likely to occur when the input belongs to an element which has `display: none` style and that causes the wrong calculation for the `padding-left`

**Comment by rmstox** [comment] 2020-02-19 20:35
Yep, the problem definitely occurs when the form field is inside a `display: none` DIV. So far, nothing related to the load order. I played around with two divs and the the iti form field in the `display: none` DIV got a `style="padding-left: 1444px;`applied. Which is huge!

**Comment by picks44** [comment] 2020-05-14 13:26
Any solution for this ?

**Comment by brazenvoid** [comment] 2020-05-14 16:05
> Any solution for this ?

Use the solution by Zippovich2

Works great for me. Wish it was part of the plugin already. Its the second time I wasted so much time trying to correct it when I had it already resolved in a previous one.

**Comment by brazenvoid** [comment] 2020-05-14 16:43
Just encountered the issue variation mentioned by @TheRealThor 

Currently there is no solution to this aside from adding custom JS and manually changing the padding on first show event to get it back to sane values. 

@jackocnr As this variation is not a load order issue, is there a way to initiate recalculation for this padding through the plugin itself? 
Or perhaps this variation can be catered in the plugin as having an input inside a hidden div is a valid use case.

**Comment by jackocnr** [comment] 2020-05-25 10:42
I'll re-open this as so many people are experiencing the issue.

If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by JavierPAYTEF** [comment] 2020-05-25 18:18
This emulates the issue when you load the CSS after the javascript: https://codepen.io/JavierPAYTEF/pen/LYpvOJW

I know it might seem dumb at first, but with the newer frameworks that mangle the javascripts in bundles and dynamically load all the assets from within the javascript as well, sometimes you can't be sure when your CSS loads unless you explicitly think about it.

This issue is also kind of obscure because you wouldn't expect the input to default to screen width because of a load order issue. I'm not sure how to fix this properly, but I think a good start would be removing the screen width as the default, hardcoding some kind of max width would be a lot better even if it's not perfect.

**Comment by TheRealThor** [comment] 2020-05-25 18:42
For the people that need a quick fix: I used a workaround for this with opacity:0 as style attribute and a class on the DIV in which the iti field lies like that:
```
.hidden {
   position: absolute !important;
   top: -8888px !important;
   left: -8888px !important;
}
```

To make the DIV visible I'll toggle the class and fade the opacity to 1 (with jQuery)
`$('#div_name').removeClass("hidden").fadeTo('slow',1);`

**Comment by jackocnr** [comment] 2020-05-26 09:33
@JavierPAYTEF thanks for the Codepen.

I find this situation really strange - that you are managing to load the plugin JS **and** your custom initialisation JS before the plugin CSS has loaded.

Please can you give more info about your specific setup? And everyone else in this thread - what setup are you using that means the plugin CSS is loading after both the plugin JS **and** the your custom initialisation code?

Is there no way for you to load the plugin CSS earlier? Or delay initialising the plugin until later?

**If** there's really no way to avoid this issue, and it's affecting lots of people, then I suppose we could add some kind of workaround. Where we're calculating `selectedFlagWidth`, we could check if the CSS has loaded yet using `getComputedStyle` - if it has loaded then we can proceed with `getHiddenSelectedFlagWidth`, but if it hasn't loaded then we can default to some sane value. But note that this will often be wrong, and will look crap e.g. if you init the input with phone number with a long dial code vs a short dial code - those values need different amounts of padding - that's the point of this feature - so some generic default will always look bad in some cases. So this doesn't solve the issue, it just makes it less bad. The only way to solve this issue is to load the CSS before you run the plugin init code.

**Comment by brazenvoid** [comment] 2020-05-26 21:30
@jackocnr For me, the issue occurs when the input is inside a hidden div, there are no issues with CSS loading, I am doing it before all JS loads. 

I have seen this calculated width issue with select2 as well (https://github.com/select2/select2/issues/5585). 

What they do for multi-select mode is to dynamically render placeholder inside their markup. What they cite as the reason is when an element is inside a hidden element, the width is supplied as zero to their formulae. Their formulae then produce a zero width, yours though has other positive values like screen width added to them, thus, achieving the other extreme... :)

They have acknowledged it and have produced a beta of the solution which well though is still incomplete, but has many core changes.

**Comment by jackocnr** [comment] 2020-05-26 21:56
@brazenvoid but this is exactly what the `_getHiddenSelectedFlagWidth` function is for - it injects a new selected flag into the `<body>` with `visibility:hidden` styling, so you can't see it, but it's there in the DOM, so it can calculate the width.

Are you sure you're using the latest version of the plugin?

If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by Zippovich2** [comment] 2020-05-27 07:21
@jackocnr `_getHiddenSelectedFlagWidth` can work incorrect with some CSS code. 
I create a pen to reproduce bug from my project https://codepen.io/zippovich2/pen/XWmwaEp

Of course, this bug appears because of my CSS but it can be easily fixed with 1 line in this plugin to avoid the influence of third-party CSS:
```js
value: function _getHiddenSelectedFlagWidth() {
    // to get the right styling to apply, all we need is a shallow clone of the container,
    // and then to inject a deep clone of the selectedFlag element
    var containerClone = this.telInput.parentNode.cloneNode();
    containerClone.style.visibility = "hidden";
    containerClone.style.width = "auto"; // This line
    document.body.appendChild(containerClone);
    var selectedFlagClone = this.selectedFlag.cloneNode(true);
    containerClone.appendChild(selectedFlagClone);
    var width = selectedFlagClone.offsetWidth;
    containerClone.parentNode.removeChild(containerClone);
    return width;
}
```
And maybe it can fix bugs for those who use it with React, Angular etc.

**Comment by jackocnr** [comment] 2020-05-27 10:09
Thanks for the Codepen @Zippovich2, that really helps.

So there are 2 distinct issues going on here, so I've decided to create 2 new issues for them, so they can be discussed individually, and I can get an idea of how many people are experiencing them.

[Padding-left issue with separateDialCode, hidden input, and 100% width container](https://github.com/jackocnr/intl-tel-input/issues/1098)

and

[Padding-left issue with separateDialCode and loading plugin CSS after initialising the plugin](https://github.com/jackocnr/intl-tel-input/issues/1099)

Let's please continue the discussion in those issues. Thanks.

**Closed by jackocnr** 2020-05-27 10:09 UTC

**Comment by ruleboy21** [comment] 2020-07-28 19:05
I had the same issue but this worked for me

```
$('#modal').on('shown.bs.modal', function(){
  let phone = $('#phone'), lPadd = phone.prev('.iti__flag-container').width() + 6;
  phone.css('padding-left', lPadd);
});
```
Hope it helps

**Comment by asilmb** [comment] 2020-11-20 13:34
That work to me 
 input.addEventListener("countrychange", function() {
          $(input).attr('style', 'padding-left: 100px;');
        });

**Comment by brazenvoid** [comment] 2020-11-20 20:35
The recent versions have fixed this issue though.

**Comment by KevinCarnaille2** [comment] 2020-12-15 17:12
> The recent versions have fixed this issue though.

Not for me, using the latest one :)

**Comment by Morbids** [comment] 2023-08-17 23:32
The problem appears
