### ISSUE TITLE
NANP Group (+1) problem with Canada.. Dominican Republic, etc

### ISSUE THREAD

**Issue by SixSense2022** [jackocnr/intl-tel-input#1404] opened 2023-03-01 20:44 UTC
### Steps to reproduce
1.  Select Canada
2.  Put any number
3.  You get the default country (US). Same with "DO" and maybe more countries from the nanp group. 

### Expected behaviour
There is a problem with phones from "Nanp Group (+1 countries list)". If you select "Canada" or "Dominican Republic" or (maybe are more countries (+1) with problems), if you type anything, you get the default country selected(US).
Nanp group +1: "**US AG AI AS BB BM BS CA DM DO GD GU JM KN KY LC MP MS PR SX TC TT VC VG VI**"

I fix this in "intlTelInput.js" by adding BEFORE "**var isRegionlessNanpNumber**" this:
```
if (isNanp) {
 alreadySelected = true;
}
```

Can you do the same on the official script? Or at least an option to "skip nanp check" and if is true to add this fix. A lot of users will thank you.

**Comment by SixSense2022** [comment] 2023-03-06 12:18
> 

If you copy/paste these numbers jumps to the default US.
Canada: 5144951550
Dominican Republic: 8095334800

**Comment by jackocnr** [comment] 2023-03-06 12:30
I can't reproduce that issue on the demo site: https://intl-tel-input.com/

Can you?

**Comment by jackocnr** [comment] 2023-03-06 12:45
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by SixSense2022** [comment] 2023-03-06 14:55
@jackocnr I made a codepen for 17.0.19 (is the version i'm using now in my website) with default CA and **is working just fine**.
[https://codepen.io/sixsense/pen/RwYZoJO](url)

Then I don't know where can be the problem. Anyway, excluding the nanp check solved the problem on my website.

**Comment by jackocnr** [comment] 2023-03-10 11:15
Sounds like it's something in your own code then. Closing for now. Feel free to re-open if you can repro the issue in a codepen.

**Closed by jackocnr** 2023-03-10 11:15 UTC
