### ISSUE TITLE
Cannot use 'in' operator to search for 'intlTelInputUtils' in undefined

### ISSUE THREAD

**Issue by akvaliya** [jackocnr/intl-tel-input#961] opened 2019-09-02 16:43 UTC
### Steps to reproduce
1.  Load util.js from node_modules

### Expected behaviour
There should not be any error

### Actual behaviour
Getting below error in browser console
```
utils.js:1 Uncaught TypeError: Cannot use 'in' operator to search for 'intlTelInputUtils' in undefined
    at m (utils.js:1)
    at utils.js:443
    at Object../node_modules/ng2-tel-input/node_modules/intl-tel-input/build/js/utils.js (utils.js:447)
    at __webpack_require__ (bootstrap:84)
    at Module../node_modules/ng2-tel-input/src/ng2-tel-input.js (ng2-tel-input.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module../node_modules/ng2-tel-input/src/ng2-tel-input.module.js (ng2-tel-input.module.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module../node_modules/ng2-tel-input/ng2-tel-input.js (ng2-tel-input.js:1)
    at __webpack_require__ (bootstrap:84)
```

**Comment by jackocnr** [comment] 2019-09-02 17:06
Duplicate of #958

**Closed by jackocnr** 2019-09-02 17:06 UTC
