### ISSUE TITLE
Firefox Android - incorrect caret position when typing number in a masked field

### ISSUE THREAD

**Issue by mpiasta-ca** [jackocnr/intl-tel-input#190] opened 2015-03-23 21:48 UTC
When you [try the demo](http://jackocnr.com/intl-tel-input.html) on an Android device within [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en) (which is a noteable browser, because it allows you to use [Adblock Plus](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/) on your Android device lol), as you try to type a phone number, when the masking adds characters into the field around your number, the cursor skips to the wrong position.

ie. as you type `6045551234`... it types in as `(604) 432-1555`. Because as you type `604`, masking adds a `-` to make it `604-`. But then every digit you type goes before the `-`, so... `6045-`, `60455-`, `604555-`, `6041555-`, `(604)215-55`, etc...

Works fine on Android Chrome however.

**Comment by jackocnr** [comment] 2015-03-24 00:53
Confirmed, but according to this [Mobile/Tablet Browser Market Share](https://www.netmarketshare.com/browser-market-share.aspx?qprid=0&qpcustomd=1) breakdown, Firefox currently has 0.67% of the mobile market share, so this isn't super high priority. It will mostly likely be a case of finding or filing a bug with their [bugzilla](https://bugzilla.mozilla.org/buglist.cgi?product=Firefox%20for%20Android&component=Keyboards%20and%20IME&resolution=---), if anyone has time to do some [remote debugging](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Firefox_for_Android) and figure out where the problem is.

**Comment by sime** [comment] 2015-03-24 07:10
I've come across this aswell.

FF is my default Android browser, so I'll attempt to do some remote debugging or testing of patches if they arise.

**Comment by mpiasta-ca** [comment] 2015-03-24 17:10
It's worth mentioning that Firefox Windows works, so that's quite the (╯°□°）╯︵ ┻━┻

**Comment by jackocnr** [comment] 2015-03-24 17:46
Lol ok thanks guys. @sime thanks for offering to do some remote debugging. Do let us know what you find.

**Comment by sime** [comment] 2015-04-08 22:34
I have briefly taken a look at `_handleInputKey`. To my eyes it is behaving correctly. Initial I was suspicious about `input.setSelectionRange`, but it seems to be find.

What I'll look into next is if any additional events are jumping in when they shouldn't as the caret is visibly in the right spot at one point before it settles.

PS disabling `autoFormat` is a workaround to this problem.

**Comment by sime** [comment] 2015-04-09 07:24
Hrm. Still looking into this. I thought I could influence the behaviour by removing all occurrences of `input.setSelectionRange`, but no difference experienced.

**Comment by sime** [comment] 2015-04-09 22:07
I'm leaving this for now, and just disabling `autoFormat` on Firefox for Android using this detection:

```js
var user_agent = navigator.userAgent.toLowerCase(),
  is_firefox = user_agent.indexOf('firefox') > -1,
  is_android = user_agent.indexOf('android') > -1,
  is_firefox_android = is_firefox && is_android;
```

**Comment by mpiasta-ca** [comment] 2015-04-12 18:35
Can someone [file a bug with Mozilla](https://bugzilla.mozilla.org)? Just link them to [the demo website](http://jackocnr.com/intl-tel-input.html), and let them know it works in Firefox Windows, but fails in Firefox Android.

**Comment by sime** [comment] 2015-04-12 19:36
Logged. https://bugzilla.mozilla.org/show_bug.cgi?id=1153668

**Comment by iamstarkov** [comment] 2015-11-24 16:20
@sime voted for this issue in the firefox bug-tracker, everybody can do it as well, just sign in with github account

**Comment by jackocnr** [comment] 2015-11-24 17:40
Good idea! I just voted - please all others do the same!

**Comment by jackocnr** [comment] 2016-01-11 16:09
Good news! Apparently this is fixed in Firefox Beta 44 - can anyone confirm?

**Comment by sime** [comment] 2016-01-11 21:52
Looks like it is working form me. Will wait re-confirm with Firefox 44 is GA.

**Comment by jackocnr** [comment] 2016-02-04 02:19
@sime I believe v44 is out now - could you confirm this is fixed?

**Comment by sime** [comment] 2016-02-04 05:42
I don't believe the demo is valid anymore. It seems that autoFormat is disabled.

**Comment by sime** [comment] 2016-02-04 05:53
I removed the `is_firefox_android` hack from my site and it works (v7.0.2) as described in the above Mozilla bug.

But the cursor is jumps back, which may confuse the user.

Below I demonstrate the cursor position with the pipe (|) symbol.

Input: `+1234`
Expected: `+1 234-|`
Experienced: `+1 234|-`

Input: `+61234`
Expected: `+61 2 34|`
Experienced: `+61 2 3|4`

The cursor jumps a character before or after formatting has occurred.

Though I think I can say this particular issue could be closed.

**Comment by jackocnr** [comment] 2016-02-05 22:12
@sime thanks for taking a look. That actually looks like the original issue to me - are you sure you're on v44?

**Comment by sime** [comment] 2016-02-05 22:31
@jackocnr Yes I'm on v44.

The original bug as described on Bugzilla is the ordering of the number is wrong. Not specifically the cursor.

Ordering matters the most :)

**Comment by jackocnr** [comment] 2016-02-05 23:24
@sime what's the end result if you type 6045551234?

Do you get the correct result: (604) 555-1234

Or the op's backwards issue: (604) 432-1555

**Comment by sime** [comment] 2016-02-05 23:30
I get the correct result.

**Comment by jackocnr** [comment] 2016-02-06 01:53
Ok brilliant. Then I'll close this. Please could you open a new issue for the cursor problem?

**Closed by jackocnr** 2016-02-06 01:53 UTC
Labels: bug

**Comment by Thiltal** [comment] 2017-11-21 10:03
Was the issue of cursor problem opened? Please link it?
