### ISSUE TITLE
Phone number validation coming back "undefined" for certain numbers

### ISSUE THREAD

**Issue by multiwebinc** [jackocnr/intl-tel-input#1044] opened 2020-03-06 00:27 UTC
I tried the example [here](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html) and reproduced it myself with the following code:

``` javascript
var errorMsg = document.querySelector("#intl-phone-error");
var errorMap = ["Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];
var reset = function() {
    telInput.classList.remove("error");
    errorMsg.innerHTML = "";
    errorMsg.classList.remove("visible");
};

telInput.addEventListener('blur', function() {
    reset();
    if (telInput.value.trim()) {
        if (!iti.isValidNumber()) {
            telInput.classList.add("error");
            var errorCode = iti.getValidationError();
            console.log(errorCode)
            errorMsg.innerHTML = errorMap[errorCode];
            errorMsg.classList.add("visible");
        }
    }
});
```

For the number +506 888 888 888 it outputs "undefined" to the screen. In this case `iti.getValidationError()` is returning `5`, and is therefore not in the `errorMap` array.

**Comment by jackocnr** [comment] 2020-03-09 11:19
Duplicate of #937

**Closed by jackocnr** 2020-03-09 11:19 UTC
